//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adoProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rysi_adoEntities : DbContext
    {
        public rysi_adoEntities()
            : base("name=rysi_adoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<autobus> autobuses { get; set; }
        public DbSet<boleto> boletos { get; set; }
        public DbSet<ciudade> ciudades { get; set; }
        public DbSet<corrida> corridas { get; set; }
        public DbSet<estado> estados { get; set; }
        public DbSet<itineriario> itineriarios { get; set; }
        public DbSet<terminale> terminales { get; set; }
    }
}
