//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class boleto
    {
        public string folio { get; set; }
        public string corrida { get; set; }
        public int tipoboleto { get; set; }
        public string pasajero { get; set; }
        public int asiento { get; set; }
        public decimal precio { get; set; }
        public decimal iva { get; set; }
        public string estatus { get; set; }
    
        public virtual corrida corrida1 { get; set; }
    }
}
