//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class corrida
    {
        public corrida()
        {
            this.boletos = new HashSet<boleto>();
        }
    
        public string folio { get; set; }
        public int itinerario { get; set; }
        public System.DateTime fecha { get; set; }
        public string servicio { get; set; }
        public string estatus { get; set; }
        public decimal precio { get; set; }
        public decimal iva { get; set; }
        public decimal total { get; set; }
        public int disponibles { get; set; }

        public string origen { get; set; }
        public string destino { get; set; }
    
        public virtual ICollection<boleto> boletos { get; set; }
        public virtual itineriario itineriario { get; set; }
    }
}
