//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class itineriario
    {
        public itineriario()
        {
            this.corridas = new HashSet<corrida>();
        }
    
        public int id { get; set; }
        public int origen { get; set; }
        public int destino { get; set; }
        public Nullable<System.TimeSpan> horasalida { get; set; }
        public Nullable<float> estimadohrs { get; set; }
    
        public virtual ICollection<corrida> corridas { get; set; }
        public virtual terminale terminale { get; set; }
        public virtual terminale terminale1 { get; set; }
    }
}
