//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class terminale
    {
        public terminale()
        {
            this.itineriarios = new HashSet<itineriario>();
            this.itineriarios1 = new HashSet<itineriario>();
        }
    
        public int idterminal { get; set; }
        public string nombre { get; set; }
        public int idciudad { get; set; }
        public string codigoterminal { get; set; }
    
        public virtual ciudade ciudade { get; set; }
        public virtual ICollection<itineriario> itineriarios { get; set; }
        public virtual ICollection<itineriario> itineriarios1 { get; set; }
    }
}
